name: Build and Test
on:
    push:
        branch-ignore:
            - main
jobs:
    build-and-test:
        concurrency: ci-${{ github.ref }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install, Build, and Test
              run: |
                  npm ci
                  npm run format:check
                  cd packages/vue-app
                  npm run check
